#!/usr/bin/env python3
import json, itertools
from collections import defaultdict

nat = json.load(open("nations.json"))

# Formables are INCLUDED, just flagged (must be formed before its tree is accessible).
FORMABLE = {
    "SCA","MGE","YUA","GLH","ILK","RUM","AUH","QNG","PLC","SPA","MUG","GBR",
    "GER","ITA","HLR","ROM","NED","HND","RFR","TIM","PRU","HSA","KOW","KSC",
    "ARL","BYZ","ROU","KON","MFL","ADU",
}
MIN_MISSIONS = 30

def core_regions(d, min_w=3, frac=0.12):
    rw = d["rweight"]
    if not rw:
        return set()
    thr = max(min_w, frac * d["missions"])
    return {r for r, w in rw.items() if w >= thr}

def top_super(d):
    sw = d.get("sweight", {})
    if not sw:
        return "?"
    return max(sw.items(), key=lambda kv: kv[1])[0]

# collapse exact-duplicate trees (same missions + same regions) into one entry
groups = {}
order = []
for t, d in sorted(nat.items(), key=lambda kv: -kv[1]["missions"]):
    if d["missions"] < MIN_MISSIONS:
        continue
    fp = (d["missions"], tuple(sorted(d["regions"])), tuple(sorted(d["series"])))
    if fp in groups:
        groups[fp].append(t)
    else:
        groups[fp] = [t]
        order.append((fp, t, d))

info = {}
for fp, t, d in order:
    info[t] = {
        "name": d["name"], "missions": d["missions"],
        "core": core_regions(d), "allreg": set(d["regions"]),
        "super": top_super(d), "series": set(d["series"]),
        "dlc": d["dlc"], "aliases": [x for x in groups[fp] if x != t],
        "formable": t in FORMABLE,
    }
tags = list(info)

def size_similar(a, b, ratio=0.72, absdiff=12):
    ma, mb = info[a]["missions"], info[b]["missions"]
    lo, hi = min(ma, mb), max(ma, mb)
    return (lo / hi >= ratio) or (hi - lo <= absdiff)

def tier(m):
    if m >= 90: return "XXL (90+)"
    if m >= 60: return "XL (60-89)"
    if m >= 50: return "L (50-59)"
    if m >= 44: return "M (44-49)"
    if m >= 38: return "S (38-43)"
    return "XS (30-37)"

pairs = []
for a, b in itertools.combinations(tags, 2):
    core_o = info[a]["core"] & info[b]["core"]
    shared_s = info[a]["series"] & info[b]["series"]
    all_o = info[a]["allreg"] & info[b]["allreg"]
    if shared_s:        # same lineage / formable chain -> not opponents
        continue
    if core_o:          # fight over the same core land
        continue
    if not size_similar(a, b):
        continue
    pairs.append((a, b, len(all_o), sorted(all_o)))

def pkey(p):
    a, b, ov, _ = p
    return (ov, abs(info[a]["missions"] - info[b]["missions"]))
pairs.sort(key=pkey)

tags_sorted = sorted(tags, key=lambda t: -info[t]["missions"])

print("CANDIDATES (>=%d missions; formables INCLUDED & flagged; exact dupes collapsed): %d" % (MIN_MISSIONS, len(tags)))
print(f"{'tag':4} {'F':1} {'name':22} {'miss':>4} {'tier':10} {'theater':16} {'#core':>5}  aliases")
for t in tags_sorted:
    i = info[t]
    f = "F" if i["formable"] else " "
    th = i["super"].replace("_superregion","")
    print(f"{t:4} {f:1} {i['name'][:22]:22} {i['missions']:>4} {tier(i['missions']):10} {th[:16]:16} {len(i['core']):>5}  {','.join(i['aliases'][:6])}")

print(f"\nCLEAN NON-CONFLICTING + SIZE-SIMILAR PAIRS: {len(pairs)}")

# ---- markdown report ----
L = []
L.append("# EU4 mission-tree matchup analysis (all DLC enabled)\n")
L.append("Generated by parsing your installed game files (`missions/*.txt`, `map/{area,region,superregion}.txt`).\n")
L.append("**Definitions**")
L.append("- **Missions** = total missions across every *active, tag-locked* mission series that tag can see. Legacy pre-DLC trees (hidden because you own the newer DLC) are excluded.")
L.append("- **F** = formable nation (you must form it in-game before its mission tree unlocks — a time/difficulty cost, not a 1444 start).")
L.append("- **Theater** = dominant superregion by mission focus.")
L.append("- **Core regions** = regions targeted by enough missions to be a real objective (weight ≥ max(3, 12% of the nation's missions)).")
L.append("- A **clean matchup** requires: (1) zero shared *core* regions, (2) no shared mission series (not the same lineage/formable chain), (3) similar size (smaller/larger ≥ 0.72 **or** within 12 missions).")
L.append("- **Size is objective (mission count). Difficulty is NOT encoded in the files** — treat the count as the race-length proxy and judge difficulty separately.\n")
L.append("> Parser caveats: a few nations whose trees use unusual `potential` patterns (e.g. Mughals, Ming) are under-counted here; numbers reflect tag-locked series only, not generic/shared trees a nation can also pursue.\n")

L.append("## Candidate nations\n")
L.append("| Tag | Nation | Formable | Missions | Tier | Theater | Core regions | Identical-tree tags |")
L.append("|---|---|:--:|---:|---|---|---:|---|")
for t in tags_sorted:
    i = info[t]
    th = i["super"].replace("_superregion","")
    L.append(f"| {t} | {i['name']} | {'✓' if i['formable'] else ''} | {i['missions']} | {tier(i['missions'])} | {th} | {len(i['core'])} | {', '.join(i['aliases'])} |")

L.append("\n## All clean non-conflicting, size-similar matchups\n")
L.append("Sorted by least total regional overlap, then closest size. `Δ` = mission-count gap. `ov` = # regions both footprints touch at all (lower = cleaner). `F` marks a formable side.\n")
L.append("| A | F | miss | B | F | miss | Δ | ov | theaters |")
L.append("|---|:--:|---:|---|:--:|---:|---:|---:|---|")
for a, b, ov, _ in pairs:
    ia, ib = info[a], info[b]
    d = abs(ia["missions"] - ib["missions"])
    th = f"{ia['super'].replace('_superregion','')} / {ib['super'].replace('_superregion','')}"
    L.append(f"| {ia['name']} ({a}) | {'✓' if ia['formable'] else ''} | {ia['missions']} | {ib['name']} ({b}) | {'✓' if ib['formable'] else ''} | {ib['missions']} | {d} | {ov} | {th} |")

open("REPORT.md","w").write("\n".join(L)+"\n")
print("wrote REPORT.md")
